version: "3"
services:
  pacs:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
    restart: always
    networks:
      - pacs

networks:
  pacs:
    external: true
